jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-haskell@v1"
        with:
          cabal-version: "3.0"
          ghc-version: "8.6.5"
          operating-system: ubuntu-18.04
      - name: "Install dhall"
        run: |
          cabal update
          cabal install dhall
      - name: "Check Dhall"
        run: |
          export PATH=$HOME/.cabal/bin:$PATH
          dhall --file haskell-ci.dhall
          dhall --file example.dhall
          dhall --file self-ci.dhall
          dhall --file ats-ci.dhall
          dhall --file toml-ci.dhall
name: "Haskell CI"
on:
  - push
